using RayTracingWeekend

include("chapters/01_imagegradient.jl")
include("chapters/09_skycolor.jl")
include("chapters/10_sphere.jl")
include("chapters/11_spherenormal.jl")
include("chapters/24_twospheres.jl")
include("chapters/30_antialiasing.jl")
include("chapters/40_diffusion.jl")
include("chapters/50_metal.jl")
include("chapters/60_dielectrics.jl")
include("chapters/63_new_camera.jl")
include("chapters/64_distant_view.jl")
include("chapters/68_defocus_blur.jl")
include("chapters/70_final_scene.jl")